name: region-to-share
base: core22
version: '1.0.7'
summary: Share selected screen regions - perfect for ultrawide screens
description: |
  Region-to-Share allows you to select a specific area of your screen
  and display it in a window that you can share directly 
  in your video conferencing applications (Google Meet, Teams, Discord, etc.).

  Features:
  - Interactive screen region selection (Wayland has blank screen issue)
  - High-performance real-time display (up to 240 FPS)
  - Advanced performance monitoring with --perf flag
  - Configurable frame rates and capture optimization
  - Wayland via xdg-desktop-portal/PipeWire (>=1.0.5)
  - X11 via MSS with optimized capture pipeline
  - Pause/resume capture with transparency controls
  - Auto update on screen changes
  - Remember last region for quick reuse
  - Auto-background mode for streamlined workflow

grade: stable
confinement: strict

website: https://github.com/solarpush/region-to-share/blob/main/README.md
issues: https://github.com/solarpush/region-to-share/issues
source-code: https://github.com/solarpush/region-to-share

donation:
  - https://coff.ee/solarpush

architectures:
  - build-on: amd64

apps:
  region-to-share:
    command: bin/region-to-share
    desktop: usr/share/applications/region-to-share.desktop
    # extensions: [gnome]   # REMOVED: Causes GTK2/GTK3 conflicts
    plugs:
      - desktop                # portals access
      - desktop-legacy         # for older desktop integration
      - wayland                # Wayland socket
      - x11                    # optional fallback on X11
      - opengl                 # OpenGL/Mesa drivers access
      - hardware-observe       # Hardware information access
      - screen-inhibit-control
      - home
      - network
      - unity7                 # for X11 desktop integration
      - gsettings              # for accessing desktop settings
    environment:
      # Prefer Wayland, fall back to X11 if needed
      QT_QPA_PLATFORM: "wayland;xcb"
      QTWEBENGINE_DISABLE_SANDBOX: "1"
      
      # PipeWire configuration
      PIPEWIRE_CONFIG_DIR: "$SNAP/usr/share/pipewire"
      PIPEWIRE_MODULE_DIR: "$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pipewire-0.3"
      SPA_PLUGIN_DIR: "$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/spa-0.2"
      
      # GStreamer configuration  
      GST_PLUGIN_PATH: "$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/gstreamer-1.0"
      GST_PLUGIN_SYSTEM_PATH: "$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/gstreamer-1.0"

parts:
  region-to-share:
    plugin: python
    source: .
    source-type: local
    python-packages:
      - PyQt5==5.15.11
      - mss==10.0.0
      - dbus-python==1.3.2
      - psutil
    build-packages:
      - python3-dev
      - python3-pip
      - python3-setuptools
      - python3-wheel
      - pkg-config
      - libdbus-1-dev
      - libdbus-glib-1-dev
      - libx11-dev
      - libxext-dev
      - libxrandr-dev
      - libxss-dev
      - libqt5x11extras5-dev
      - libgstreamer1.0-dev
      - libgstreamer-plugins-base1.0-dev
      - libgirepository1.0-dev
      - libglib2.0-dev
      - libcairo2-dev
    stage-packages:
      # Python runtime
      - python3
      - python3-gi
      - python3-gi-cairo
      - python3-dbus

      # PipeWire client (daemon provided by host)
      - libpipewire-0.3-0
      - libspa-0.2-modules
      
      # PulseAudio libraries (needed by GStreamer)
      - libpulse0

      # GStreamer (keep minimal; add good/bad/ugly only if required)
      - libgstreamer1.0-0
      - gstreamer1.0-plugins-base
      - gstreamer1.0-plugins-good
      
      # GStreamer PipeWire plugin - ESSENTIEL pour pipewiresrc
      - gstreamer1.0-pipewire

      # Qt5 for PyQt5
      - libqt5core5a
      - libqt5gui5
      - libqt5widgets5
      - libqt5x11extras5
      - libqt5dbus5
      - qt5-gtk-platformtheme
      
      # Essential GLib libraries (minimal set, correct package names)
      - libglib2.0-0
      - libgdk-pixbuf-2.0-0
      
      # PipeWire configuration files
      - pipewire-media-session
      
      # Mesa/OpenGL libraries for graphics acceleration
      - libgl1-mesa-glx
      - libgl1-mesa-dri
      - mesa-utils

      # GObject Introspection (dbus-python/gi)
      - gir1.2-gtk-3.0
      - gir1.2-glib-2.0
      - gir1.2-gstreamer-1.0
      - gir1.2-gst-plugins-base-1.0
      - libgirepository-1.0-1

      # System deps X11/Wayland
      - libx11-6
      - libxrandr2
      - libxss1
      - libwayland-client0
      - libxcb-xinerama0
      - libxcb-icccm4
      - libxcb-image0
      - libxcb-keysyms1
      - libxcb-randr0
      - libxcb-render-util0
      - libxcb-xkb1
    override-pull: |
      craftctl default
      rm -rf $CRAFT_PART_SRC/venv_region* || true
      find $CRAFT_PART_SRC -name "__pycache__" -exec rm -rf {} + 2>/dev/null || true
      find $CRAFT_PART_SRC -name "*.pyc" -delete 2>/dev/null || true
    override-build: |
      craftctl default

      # Install package code into the snap's Python path
      mkdir -p $CRAFT_PART_INSTALL/lib/python3.10/site-packages/region_to_share
      cp -r region_to_share/* $CRAFT_PART_INSTALL/lib/python3.10/site-packages/region_to_share/

      # Runtime launcher
      mkdir -p $CRAFT_PART_INSTALL/bin
      cat > $CRAFT_PART_INSTALL/bin/region-to-share << 'SCRIPT_EOF'
      #!/bin/bash
      
      # Completely disable all GTK-related components that cause conflicts
      unset GTK_MODULES GTK2_RC_FILES GTK_IM_MODULE XMODIFIERS
      export NO_AT_BRIDGE=1
      export GTK_MODULES=""
      
      # Disable GSettings completely to avoid schema warnings
      unset G_MESSAGES_DEBUG
      export GSETTINGS_BACKEND="memory"
      export GSETTINGS_SCHEMA_DIR="$SNAP/usr/share/glib-2.0/schemas"
      
      # Disable all debug output
      export QT_LOGGING_RULES="*.debug=false"
      export GST_DEBUG=0
      
      # Python paths
      export PYTHONPATH="$SNAP/lib/python3.10/site-packages:$SNAP/usr/lib/python3/dist-packages:$PYTHONPATH"
      
      # Qt5 configuration - minimal and clean
      export QT_QPA_PLATFORM="xcb"
      export QT_PLUGIN_PATH="$SNAP/lib/python3.10/site-packages/PyQt5/Qt5/plugins"
      export QT_QPA_PLATFORM_PLUGIN_PATH="$SNAP/lib/python3.10/site-packages/PyQt5/Qt5/plugins/platforms"
      export LD_LIBRARY_PATH="$SNAP/lib/python3.10/site-packages/PyQt5/Qt5/lib:$SNAP/usr/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH"
      
      # Mesa/OpenGL configuration
      export LIBGL_DRIVERS_PATH="$SNAP/usr/lib/x86_64-linux-gnu/dri:/usr/lib/x86_64-linux-gnu/dri"
      export LIBGL_ALWAYS_SOFTWARE=1  # Use software rendering if hardware fails
      
      # GStreamer for Wayland portal
      export GST_PLUGIN_PATH="$SNAP/usr/lib/x86_64-linux-gnu/gstreamer-1.0"
      export GST_PLUGIN_SYSTEM_PATH="$SNAP/usr/lib/x86_64-linux-gnu/gstreamer-1.0"
      export GI_TYPELIB_PATH="$SNAP/usr/lib/x86_64-linux-gnu/girepository-1.0:$SNAP/usr/lib/girepository-1.0"
      
      # Create cache directory
      mkdir -p "$SNAP_USER_COMMON/.cache" 2>/dev/null || true
      
      cd "$SNAP"
      exec python3 -m region_to_share.main "$@"
      SCRIPT_EOF
      chmod +x $CRAFT_PART_INSTALL/bin/region-to-share

  desktop-file:
    plugin: dump
    source: .
    organize:
      region-to-share.desktop: usr/share/applications/region-to-share.desktop
      region-to-share-64.png: usr/share/icons/hicolor/64x64/apps/region-to-share.png
      region-to-share-128.png: usr/share/icons/hicolor/128x128/apps/region-to-share.png
      region-to-share-512.png: usr/share/icons/hicolor/512x512/apps/region-to-share.png
      region-to-share.svg: usr/share/icons/hicolor/scalable/apps/region-to-share.svg
      region-to-share.png: usr/share/pixmaps/region-to-share.png
