name: region-to-share
base: core22
version: '1.0.0'
summary: Partage de zones d'écran sélectionnées dans les visioconférences
description: |
  Region-to-Share permet de sélectionner une zone spécifique de votre écran
  et de l'afficher dans une fenêtre que vous pouvez partager directement 
  dans vos applications de visioconférence (Google Meet, Teams, Discord, etc.).
  
  Fonctionnalités:
  - Sélection interactive de zones d'écran
  - Fenêtre d'affichage en temps réel (30 FPS)
  - Compatible avec toutes les applications de visioconférence
  - Interface simple et intuitive
  - Pause/reprise de la capture
  - Mise à jour automatique lors de changements d'écran

grade: stable
confinement: strict

architectures:
  - build-on: amd64

apps:
  region-to-share:
    command: bin/region-to-share
    desktop: usr/share/applications/region-to-share.desktop
    extensions: [gnome]
    plugs:
      - desktop
      - desktop-legacy
      - wayland
      - x11
      - unity7
      - home
      - network

parts:
  region-to-share:
    plugin: python
    source: .
    python-requirements:
      - requirements.txt
    build-packages:
      - python3-dev
      - python3-pip
      - libx11-dev
      - libxext-dev
      - libxrandr-dev
      - libxss-dev
      - libglib2.0-dev
      - libgtk-3-dev
      - pkg-config
      - python3-pyqt5
    stage-packages:
      - python3
      - python3-venv
      - python3-pip
      - python3-pyqt5
      - python3-opencv
      - python3-numpy
    override-build: |
      craftctl default
      mkdir -p $CRAFT_PART_INSTALL/bin
      cat > $CRAFT_PART_INSTALL/bin/region-to-share << 'EOF'
      #!/bin/bash
      cd $SNAP
      export PYTHONPATH="$SNAP/lib/python3.10/site-packages:$SNAP/usr/lib/python3/dist-packages"
      export QT_PLUGIN_PATH="$SNAP/usr/lib/x86_64-linux-gnu/qt5/plugins"
      export XDG_DATA_DIRS="$SNAP/usr/share:$XDG_DATA_DIRS"
      exec python3 -m region_to_share.main "$@"
      EOF
      chmod +x $CRAFT_PART_INSTALL/bin/region-to-share

  desktop-file:
    plugin: dump
    source: .
    organize:
      region-to-share.desktop: usr/share/applications/region-to-share.desktop
      region-to-share.png: usr/share/pixmaps/region-to-share.png
