name: region-to-share
base: core22
version: '1.0.1'
summary: Share selected screen regions in video conferences
description: |
  Region-to-Share allows you to select a specific area of your screen
  and display it in a window that you can share directly 
  in your video conferencing applications (Google Meet, Teams, Discord, etc.).
  
  Features:
  - Interactive screen region selection
  - Real-time display window (30 FPS)
  - Compatible with all video conferencing applications
  - Simple and intuitive interface
  - Pause/resume capture
  - Automatic update on screen changes

grade: stable
confinement: strict

architectures:
  - build-on: amd64

apps:
  region-to-share:
    command: bin/region-to-share
    desktop: usr/share/applications/region-to-share.desktop
    extensions: [gnome]
    plugs:
      - desktop
      - desktop-legacy
      - wayland
      - x11
      - unity7
      - home
      - network

parts:
  region-to-share:
    plugin: python
    source: .
    source-type: local
    python-requirements:
      - requirements.txt
    build-packages:
      - python3-dev
      - python3-pip
      - libx11-dev
      - libxext-dev
      - libxrandr-dev
      - libxss-dev
      - libglib2.0-dev
      - libgtk-3-dev
      - pkg-config
      - python3-pyqt5
    stage-packages:
      - python3
      - python3-venv
      - python3-pip
      - python3-pyqt5
      - python3-opencv
      - python3-numpy
    override-pull: |
      craftctl default
      # Remove local virtual environment to avoid external symlinks
      rm -rf $CRAFT_PART_SRC/venv_region
      # Also remove any potential __pycache__ directories
      find $CRAFT_PART_SRC -name "__pycache__" -exec rm -rf {} + 2>/dev/null || true
      find $CRAFT_PART_SRC -name "*.pyc" -delete 2>/dev/null || true
    override-build: |
      craftctl default
      # Ensure no virtual environment is included
      rm -rf $CRAFT_PART_SRC/venv_region* || true
      mkdir -p $CRAFT_PART_INSTALL/bin
      cat > $CRAFT_PART_INSTALL/bin/region-to-share << 'EOF'
      #!/bin/bash
      cd $SNAP
      export PYTHONPATH="$SNAP/lib/python3.10/site-packages:$SNAP/usr/lib/python3/dist-packages"
      export QT_PLUGIN_PATH="$SNAP/usr/lib/x86_64-linux-gnu/qt5/plugins"
      export XDG_DATA_DIRS="$SNAP/usr/share:$XDG_DATA_DIRS"
      exec python3 -m region_to_share.main "$@"
      EOF
      chmod +x $CRAFT_PART_INSTALL/bin/region-to-share

  desktop-file:
    plugin: dump
    source: .
    organize:
      region-to-share.desktop: usr/share/applications/region-to-share.desktop
      region-to-share.png: usr/share/pixmaps/region-to-share.png
